### ISSUE TITLE
Reorganize Conditions

### ISSUE THREAD

**Issue by B-E-T-A** [Zakarik/foundry-mm3#1]
Hey, could you reorganize the conditions in the token menu to be alphabetical? It is just a lot easier to find in the middle of a session when I know I just need to go after the alphabet.
![image](https://github.com/Zakarik/foundry-mm3/assets/14123636/2459eb28-5330-41fa-bf8f-52afb73781a9)

**Comment by Zakarik** [comment]
This will be in the next update.

A word of advice: use the "Token Action HUD" - it's always easier to assign states! The name of each state is displayed in the shortcut bar.
