### ISSUE TITLE
Option to Change Fonts to Default Foundry

### ISSUE THREAD

**Issue by TitanicViking** [Zakarik/foundry-mm3#10]
I must admit, the font that is being used for the default chat & character sheets is a bit difficult for myself to read at times(its too widely spaced & my eyes dont adjust to it easily), it would be nice if we had an option in the settings to change the whole system to the default foundry font.

**Comment by Zakarik** [comment]
I've made an update that allows you to force a font on the whole system for the GM if he wants.

**Comment by TitanicViking** [comment]
Thanks that was quick! I did notice that its still showing the old font when you post a power/advantage to chat though, so you may want to check into that.
