### ISSUE TITLE
Quality of Life Suggestions for Powers 

### ISSUE THREAD

**Issue by TitanicViking** [Zakarik/foundry-mm3#14]
Just a few suggestions I have for the powers to make them a bit easier to use for myself & my players. 

1. At present, when you attach a power to a main power, even if you click the post to chat button for the attached power, it only posts the main power. Making it so it posts the selected power with maybe a note saying "Main Power: XXX" Above it to chat would make it easier to share from peoples sheets. 
2. The roll dice feature when it posts to chat doesnt have anyway to modify the roll. Could we get some sort of option on the powers to do that like how the skills & attacks work?
3. Power Types(Standard, attack, etc) appear when you open the power, but dont on the sheet itself. Could we have some sort of note added or separate the powers by type?

**Comment by Zakarik** [comment]
This will be included in the next update.
