### ISSUE TITLE
Titles on the Character Sheet

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#17]
If it is not too much trouble I think a minor change to the character sheet would help new players navigate it. On the character sheet in the stats and skills section, Would you please add a small title "Attributes" on the Attributes window; "Defenses" on the Defenses window; a slightly larger title "Attacks" on the attacks window; "Maneuvers" for the Maneuvers window; "Speed" for the wonderful new Speed list; and "Skills" on the Skill List ?

**Comment by Zakarik** [comment]
This will be in the next update.
