### ISSUE TITLE
Combined Conditions adding Basic Conditions that are part of them.

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#18]
Can you make it so that when a Combined Condition (One made of several Basic Conditions) is selected, it also selects the Basic Conditions that go with it? For instance, someone under the Bound Condition is Defenseless, Immobile, and Impaired.

**Comment by Zakarik** [comment]
This will be in the next update.

**Comment by DeviousHearts** [comment]
Perfect! Thanks!
