### ISSUE TITLE
Request: EFFECT TYPES

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#19]
**EFFECT TYPES**: Possible Future Development. For attacks, have **Effect Types** be selectable according to **Damage**, **Affliction**, or **Other**. 
If **Damage** is the Effect Type, then a failed Toughness Roll delivers the appropriate amount of damage to the target according to the number of Successes
**Affliction** will have a selectable Resistance for the user to choose from (Parry, Dodge, Fortitude, Toughness, Will, etc) and then empty boxes for Fail by 1 degree, two degrees, and three degrees. If The Condition is a recognized one by name, then the system will assign the appropriate Condition to the target depending on how poorly they failed by.
**Other** is going to have a selectable resistance like Affliction but no info for conditions as this would be for special attacks like Teleport other and the like.

**Comment by Zakarik** [comment]
Integrated in the latest update.
