### ISSUE TITLE
Request: Separate Power name from Effect

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#22]
On the character sheet, it has the power name and then the effect but this often gets clipped off to the side. 
![image](https://github.com/Zakarik/foundry-mm3/assets/138895824/7784de7d-99d2-4977-a26b-65d07ac84e44)
Would it be possible to have the listed Power Effect below the name so that if the name is obscure, we can instantly tell what type of effect it is based on. 

So, instead of this, 
![Power 1 copy](https://github.com/Zakarik/foundry-mm3/assets/138895824/a3ec41f0-60f1-43f9-9c72-c7f073508481)

we would get 
![Untitled-1](https://github.com/Zakarik/foundry-mm3/assets/138895824/36d727b3-83ec-4876-b0d0-474073559fa8)

and collapsed, instead of this:
![Power 1 collapsed](https://github.com/Zakarik/foundry-mm3/assets/138895824/03a568c0-3e25-4185-ab94-2906630b72a0)

We would get this:
![Power 2 collapsed](https://github.com/Zakarik/foundry-mm3/assets/138895824/357342c7-1ee8-4d14-9217-180680eb4c80)

**Comment by TitanicViking** [comment]
I think this would be a huge improvement on labeling powers :)

**Comment by Zakarik** [comment]
It will be on the next update.
