### ISSUE TITLE
Character Sheets Wont Open

### ISSUE THREAD

**Issue by TitanicViking** [Zakarik/foundry-mm3#24]
Noticed that for some reason, sometimes character sheets become unopenable. 

I've seen 2 players this happen to. One last session & the other in todays session, but thankfully we had some backups to restore their old sheet. 

Not sure what it causing this as I wasnt able to duplicate it, but it happened live to one of my players & now his sheet wont open when clicked from the actors directory. 

System Version 1.25.1
Foundry 10.303

**Comment by TitanicViking** [comment]
Noticed after that there was a ton of errors in the console, so attaching those here. 
[localhost-1692401162246.log](https://github.com/Zakarik/foundry-mm3/files/12384450/localhost-1692401162246.log)

**Comment by Zakarik** [comment]
Do you have an export of the characters who have a problem? Could you upload them somewhere, so I can investigate precisely?

**Comment by Zakarik** [comment]
Fixed !

**Comment by TitanicViking** [comment]
> Do you have an export of the characters who have a problem? Could you upload them somewhere, so I can investigate precisely?

Sorry just saw this. I Installed the new update & had kept one of the broken sheets for testing, but it seems to still be broken. I exported the file here so you can take a look at it. It had less errors this time though! Thanks for all your hard work on this so quick :) 

I did have to change the file type on the .json to .log to get it to upload, so just change that back. 

[
[2nd log 4 broken sheet issue - localhost-1692490353315.log](https://github.com/Zakarik/foundry-mm3/files/12386912/2nd.log.4.broken.sheet.issue.-.localhost-1692490353315.log)
](url)
[broken sheet - fvtt-Actor-invictus.log](https://github.com/Zakarik/foundry-mm3/files/12386914/broken.sheet.-.fvtt-Actor-invictus.log)

**Comment by TitanicViking** [comment]
> Fixed !

Since the sheet I just uploaded for you to look over was previously broken, will this update just prevent future sheets from breaking? Totally fine if it wont restore the old broken sheet. Just wanted to confirm.

**Comment by Zakarik** [comment]
Both.

It will prévient futur sheet from breaking ans repaire alteady broken.

**Comment by TitanicViking** [comment]
> Both.
> 
> It will prévient futur sheet from breaking and repaire alteady broken.

Ah sadly it doesnt seem to have repaired the faulty sheet. Also the error in the log I attached a few minutes ago pops up when I try to click it.

**Comment by DeviousHearts** [comment]
What exactly is broken on the sheet? And have you tried reimporting anyway?

**Comment by Zakarik** [comment]
I will need the latest version of your World for search the bug.
So upload it somewhere and send the link.

**Comment by TitanicViking** [comment]
> What exactly is broken on the sheet? And have you tried reimporting anyway?

It just wont open, tried that just now on a new sheet & it breaks it the same way. 

> I will need the latest version of your World for search the bug. So upload it somewhere and send the link.

Here is the world. Under actors i've put the glitchy character sheet "Invictus" in a folder called "broken character testing"
[dc-superheroes.zip](https://github.com/Zakarik/foundry-mm3/files/12392136/dc-superheroes.zip)

**Comment by Zakarik** [comment]
I'm in V10.303 for the test.
I open the world.
I open the "Invictus" sheet in the "broken character testing" folder and there's no problem.
Are you using system version 1.25.7?
If so, try uninstalling and reinstalling the system.
Do you have any other modules for this game?

**Comment by TitanicViking** [comment]
I was on 1.25.4, no modules. Just updated to 1.25.7 & it opens now :)
Thanks for staying so on top of these updates!
