### ISSUE TITLE
Request: Add modifier box in Defense Column on the Conditions Row in the Maneuvers window

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#27]
There doesn't seem to be a box for Defense modifiers column on the row for Conditions in the Maneuvers window. 

Conditions such as Cover and Partial Cover would add to defense while Vulnerability and Defenseless would subtract.

Please add a modifier box in Defense Column on the Conditions Row in the Maneuvers window of the character sheet. :)

**Comment by Zakarik** [comment]
It will be in the next update.
