### ISSUE TITLE
Counting Successes

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#3]
When the system automatically compares the appropriate attack with the correct defense, subtracts the defense, it would be helpful to have it divide by 5 to find the appropriate number of successes.  It would be helpful to be in the attack as well so that someone with Multi-attack can clearly determine their damage bonus.

If prompted by a GM with a Skill check where the GM sets the DC, it could count successes there too as the number of successes has a bearing on how well the character did or how badly they failed in the system.

**Comment by Zakarik** [comment]
That's it for the success count.

Later, I'll do the prompt.

**Comment by Zakarik** [comment]
The DC request window will be there in the next version.

**Comment by DeviousHearts** [comment]
Thank you so much! :)
