### ISSUE TITLE
Request: Separate Tab For Power Arrays

### ISSUE THREAD

**Issue by TitanicViking** [Zakarik/foundry-mm3#32]
It would be really nice if the powers section had a divider of some sort for power arrays. Currently the way things work is nice, but it would just make it easier for players & GMs to understand what powers are stand alone powers, & which ones are arrays. 

Something like just a line break with a title at the top for the array's name so it stands out a bit more would be great. 

Example 
Array Title: Telekinetic Powers
Main Power: Move Object
Alternate Effect: Flight(Levitation)
Alternate Effect: Affliction(Mind Control)

**Comment by Zakarik** [comment]
This will be in the next update.
The title of the array will take the name of the first power.

**Comment by Zakarik** [comment]
Here's an image to illustrate what it will look like:
![image](https://github.com/Zakarik/foundry-mm3/assets/8583530/53fbd553-1c36-47de-aa09-f69925fab97a)
