### ISSUE TITLE
1.26 Showing as Invalid File

### ISSUE THREAD

**Issue by TitanicViking** [Zakarik/foundry-mm3#39]
The newest Release doesnt seem to register as a valid zip file. The file size is also significantly lower then normal, so unsure if it didnt upload correctly?

**Comment by Zakarik** [comment]
I've testée and it works, but it was really slow, so I think its a bug with Foundry.

**Comment by TitanicViking** [comment]
> I've tested and it works, but it was really slow, so I think its a bug with Foundry.

Well once I was able to download the zip from github, there is just a ton of files missing from it. 
![image](https://github.com/Zakarik/foundry-mm3/assets/118582486/ff8c24d7-fdcc-44d7-ac76-643baa8f1cd1)


And updating via foundry just gives me a critical installation error. Heres the log of the error updating through foundry. 
[localhost-1693891693819.log](https://github.com/Zakarik/foundry-mm3/files/12519155/localhost-1693891693819.log)

Cant get it to work either way.

**Comment by Zakarik** [comment]
The zip is generated by Github, so try to uninstall and reinstall the system.

**Comment by Zakarik** [comment]
Github is in trouble right now, even reigning anything in wouldn't solve the problem. It's not dependent on me, it's solely dependent on Github.

https://www.githubstatus.com/incidents/frdfpnnt85s8

**Comment by Zakarik** [comment]
It took me several minutes, but it's now possible to download the full zip file. You just have to be patient and hope it doesn't crash when you download it.

I downloaded it via Firefox, it's not very heavy, but with Github's problems, it's very very long.

![image](https://github.com/Zakarik/foundry-mm3/assets/8583530/00e3ad07-8e95-4e7e-96f4-1ae4874ca804)

Use this link : https://github.com/Zakarik/foundry-mm3/archive/1.26.0.zip

**Comment by TitanicViking** [comment]
> It took me several minutes, but it's now possible to download the full zip file. You just have to be patient and hope it doesn't crash when you download it.
> 
> I downloaded it via Firefox, it's not very heavy, but with Github's problems, it's very very long.
> 
> ![image](https://user-images.githubusercontent.com/8583530/265653837-00e3ad07-8e95-4e7e-96f4-1ae4874ca804.png)
> 
> Use this link : https://github.com/Zakarik/foundry-mm3/archive/1.26.0.zip
> 
> Or wait for Github to fix its problems.

Looks like github stopped acting weird & I got the update installed finally. Thanks!
