### ISSUE TITLE
Characters without Ability or Defense Values

### ISSUE THREAD

**Issue by Funkadelic1984** [Zakarik/foundry-mm3#4]
The character sheet doesn't seem to support characters that lack a stat like Stamina (for example contructs). Some character builds will have null values for certain stats.

After importing a charcter from HeroLab that has no Stamina or Fortitude, the value populate as "-5" rather than "-" (or some indicator of a null value). This then flows through and applies a -5 penalty to Toughness that shouldn't be there.

I assume this would also be true of intangible characters (like ghosts) that may have a null Strength value.

**Comment by Zakarik** [comment]
This will be improved in the next update.
