### ISSUE TITLE
Changing the order of the tabs

### ISSUE THREAD

**Issue by strlys** [Zakarik/foundry-mm3#5]
I believe the first tab should be "Stats & Skills" as this is the most common tab to be used. It would be very good especially for the GM, because when you open an NPC character sheet you probably want to see primarily the information on this tab.

I believe the tab order should probably be these (based on my experience/frequency of using each tab):

1. Stats & Skills
2. Powers, Advantages & Equipments
3. Information
4. Import

![image](https://github.com/Zakarik/foundry-mm3/assets/75812477/42c46ef4-85d5-484f-847d-40f65c70011d)

**Comment by Zakarik** [comment]
I've left the order of the tabs, but set the tab displayed on opening to "Stats & Skills".

This will be in the next version.
