### ISSUE TITLE
BUG: Power effect "FEATURE" seems to halt import

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#53]
In the Greenronin channel, Metroxide posted a character that stopped importing after it imported the powers. Through process of elimination, i found that when the power effect "Feature" was eliminated, then it imported just fine.

Thecharacter's name is Crusher. Her is a link to the .por file and .xml file.

https://cdn.discordapp.com/attachments/753725873340940309/1162846425613348965/Crusher.por?ex=653d6c20&is=652af720&hm=f643d2ea5b51b060c704e37e48c9418712e6f76c70bfff5c7aebb50de6406e3a&

https://discordapp.com/channels/170995199584108546/753725873340940309/1162846426766782465

**Comment by Zakarik** [comment]
I found the problem.

It will be solved in the next update.
