### ISSUE TITLE
Bug: Pulldown in chat not working properly

### ISSUE THREAD

**Issue by DeviousHearts** [Zakarik/foundry-mm3#56]
![ChatWindow-Pulldown-Bug copy](https://github.com/Zakarik/foundry-mm3/assets/138895824/b6f73040-83b7-447d-9dec-b787af2a32b7)
I noticed this when I tried to use the pulldown to reveal a previously Whispered roll to the GM to the players in the game. Normally you can use the Pulldown to reveal the roll to everyone and that works only for the most recent chat message but not for previous. The pulldown is greyed out and you cannot click on it.

**Comment by Zakarik** [comment]
It's fixed !
