### ISSUE TITLE
HQ's and Vehicles Powers & Attacks

### ISSUE THREAD

**Issue by strlys** [Zakarik/foundry-mm3#7]
For now, it's impossible for HQs and Vehicles to make attacks on other characters. But many vehicles in the system do have attacks and other powers, and HQs could have attacks/powers also.

_My suggestions:_
1. Both sheets should have a "Powers" tab for the inclusion of these powers.
2. Both sheets should have an attack section, just like the character sheet.

**Comment by Zakarik** [comment]
This will be added in the next update.
