### ISSUE TITLE
Attacks vs. Dodge not working

### ISSUE THREAD

**Issue by TlMcook** [Zakarik/foundry-mm3#72]
Issue: Attacks only target Parry.
![image](https://github.com/user-attachments/assets/69bbe4fa-9755-4e04-a5a7-0580f7261e6f)
![image](https://github.com/user-attachments/assets/a7ddc24b-cf00-4344-a347-35b9b91f2f9b)
Steps to reproduce:
1. Create an attack
2. Change the 'Type of Attack' to Damage
3. Change 'Attack Roll vs. Parry' to 'Attack Roll vs. Dodge'
4. Roll attack against target
5. See results.

**Comment by Zakarik** [comment]
Fixed in the last update (1.33.8)
