### ISSUE TITLE
Maneuver Integer Issue

### ISSUE THREAD

**Issue by TlMcook** [Zakarik/foundry-mm3#73]
Issue: Maneuver's have no limit and are not functioning correctly, additionally  attempting to fill in that blank box under Accurate Attack fails to save.
![image](https://github.com/user-attachments/assets/4310421c-d2a5-43e7-b983-3aadbb85fb36)
![image](https://github.com/user-attachments/assets/1fa161c9-1339-44e6-9339-714bd3a64f0e)
Steps to Reproduce:
1. Create a sheet
2. Change Maneuver sliders
3. Change Maneuver limits and save
4. See results

**Comment by Zakarik** [comment]
Fixed in the last update (1.33.8)
