### ISSUE TITLE
Area Attack DCs not calculating Modifiers (ver 1.35.4)

### ISSUE THREAD

**Issue by Pangaladin** [Zakarik/foundry-mm3#80]
Good morning, I love your work.

When creating an Area attack, the DC Calculation appears to not add the dodge roll modifier nor the attack rank (See figure below for modifiers)
![20240927_M M3e_PowerSettings](https://github.com/user-attachments/assets/f7b7ca64-8989-4428-a6da-990491b058eb)

Below are the DCs that appear:
![20240927_M M3e_AreaAttackDCs](https://github.com/user-attachments/assets/0c93ad34-da76-41d3-b16a-ff061d5efaf1)

If it helps, when the attacks are linked to a power the calculations work fine, it's just the modifiers in the attack window that don't seem to be added.

I'm on the discord under "Pango" if you need to contact me for further info.

**Comment by Zakarik** [comment]
It should be solved.
